name: Build and Release APK

on:
  release:
    types: [published]

jobs:
  build:
    uses: ./.github/workflows/build-apk.yml

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download APK artifact
        uses: actions/download-artifact@v4
        with:
          name: built-apk
          path: ./

      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./app-debug.apk
          asset_name: wasmedge-android-${{ github.event.release.tag_name }}.apk
          asset_content_type: application/vnd.android.package-archive
